### ISSUE TITLE
encryption dictionary: standard security handler: invalid Encrypt.O

### ISSUE THREAD

**Issue by iangudger** [seehuhn/go-pdf#1]
I tried to open an encrypted PDF created with the latest version of Adobe Acrobat and I got the error: `encryption dictionary: standard security handler: invalid Encrypt.O`.

Test file (password is `password`):
[password_protected.pdf](https://github.com/seehuhn/go-pdf/files/12412442/password_protected.pdf)

I tested with both v0.3.4 and v0.3.5-0.20230822001153-4ee04e1da286 / 4ee04e1da2863fb36d0df17539da67364c07f007.

**Comment by seehuhn** [comment]
Thank you for your report.  I tried this on MacOSX, and got mixed results: Preview opens the file fine.  Adobe Acrobat Reader did open the file for me, showing a picture of a cat, but then crashed a few seconds later!  I'll investigate ...

**Comment by iangudger** [comment]
I don't think there are any issues with the document itself. I created it for test purposes using a goofy photo of my cat using a recent version of Adobe Acrobat Pro. https://github.com/unidoc/unipdf is able to read and decrypt it, but that library has other issues.

**Comment by seehuhn** [comment]
Yes, I agree, I think my library should be able to read it, and I'll try to make the required changes.  (But still, Adobe Acrobat Reader on my mac crashed after opening the file.  The crash is not reproducible, though.)

I didn't have much time to look at this yet, but I think the problem is that the file has an "O" string which is somehow 127 bytes long, while the spec says "A byte string, 32 bytes long if the value of R is 4 or less and 48 bytes long if the value of R is 6".   The too long string has many zeros at the end, so maybe the solution is just to cut off trailing zeros, if the string is too long.  I'll need to think a bit, and maybe look what other libraries are doing here ...
